### PR TITLE
Add `ComfyUI-Impact-Pack`

### LINKED ISSUE #13: Add ComfyUI-Impact-Pack
Hi, is there any chance we could get [ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack) added to allow for Face Detailing?

### PR DESCRIPTION
**Pull request by digitaljohn**
Closes #13

### CODE REVIEW

**Comment by fofr** [comment]
Nice! Do you know if any of the custom nodes download any models on the fly?

**Comment by digitaljohn** [comment]
Likely yes, want me to identify?

**Comment by fofr** [comment]
That would be amazing, yes.

**Comment by digitaljohn** [comment]
Looks like its just these models:

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/43bca637c236aef6d9749f04d9917cac9ff3ff34/install.py#L266-L272

**Comment by fofr** [comment]
Hmm, it looks like a few things happen when you first start the impact pack:

- it runs install which updates pip packages
- it installs ultralytics, which downloads 3 further models

I'm adding some code to automatically copy the config when importing the custom node, rather than generating it, and will take from there.

Do you have some example impact pack workflows I can test with?

**Comment by fofr** [comment]
This also poses a problem:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/43bca637c236aef6d9749f04d9917cac9ff3ff34/__init__.py#L36

The .dockerignore purposefully ignores all `.git` directories as they're weight we don't need in the container. This will always attempt to delete the subpack path.

**Comment by fofr** [comment]
I've decided to fork the main repo and comment out the troublesome parts:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/compare/Main...fofr:ComfyUI-Impact-Pack:Main

**Comment by fofr** [comment]
New PR: https://github.com/fofr/cog-comfyui/pull/22

**Pull request closed without merging**
