### PR TITLE
Add `Cgem156-ComfyUI` Pack

### PR DESCRIPTION
**Pull request by yelnady**
I have added support for the `Cgem156-ComfyUI` Custom Nodes Pack, primarily to enable Attention Couple Support. This feature is incredibly useful for specifying prompts for different regions of an image while maintaining its overall integrity. It also differs from other nodes that use Latent Couple. 

It doesn't require any custom node helper functions and it doesn't depend on any specific weights. Also, all dependencies are already in cog.yaml, so I didn't touch it.

### CODE REVIEW

**Comment by fofr** [comment]
Ah, this looks nice. Do you have some simple example workflows I can test your PR with?

**Comment by yelnady** [comment]
Here's an example that simply splits the image into two halves using a mask. 

{
  "3": {
    "inputs": {
      "seed": 934436605939168,
      "steps": 4,
      "cfg": 2,
      "sampler_name": "dpmpp_sde",
      "scheduler": "karras",
      "denoise": 1,
      "model": [
        "23",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "5",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "4": {
    "inputs": {
      "ckpt_name": "dreamshaperXL_lightningDPMSDE.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "5": {
    "inputs": {
      "width": 1344,
      "height": 768,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "6": {
    "inputs": {
      "text": "boy and girl squirrels swimming in the red sea. First, A curious bushy-tailed squirrel. He has big, round eyes sparkling with mischief and a giant acorn clutched in one tiny paw. He is wearing a hat. The hat has a wide brim that dips slightly in the front, perfect for shielding his eyes from the sun. ([Pixar Style]).  ",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Left)"
    }
  },
  "7": {
    "inputs": {
      "text": "bad eyes, bad hands, no legs, no eye contact",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "10": {
    "inputs": {
      "text": "boy and girl squirrels swimming in the red sea. A tiny squirrel girl, Pixar style, with big, bright eyes sparkling with mischief. Her brown fur is accented by a cute pink bow perched on one ear, and a soft, pink ribbon adorns her bushy tail.  She has a mischievous grin and a white chest.  She's mismatched as ever, with one striped sock and one polka-dotted sock (but this time, the polka-dots are pink!). ([Pixar Style]).  ",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Right)"
    }
  },
  "11": {
    "inputs": {
      "x": 0,
      "y": 0,
      "operation": "add",
      "destination": [
        "13",
        0
      ],
      "source": [
        "12",
        0
      ]
    },
    "class_type": "MaskComposite",
    "_meta": {
      "title": "MaskComposite (Left)"
    }
  },
  "12": {
    "inputs": {
      "value": 1,
      "width": 672,
      "height": 768
    },
    "class_type": "SolidMask",
    "_meta": {
      "title": "SolidMask"
    }
  },
  "13": {
    "inputs": {
      "value": 0,
      "width": 1344,
      "height": 768
    },
    "class_type": "SolidMask",
    "_meta": {
      "title": "SolidMask"
    }
  },
  "14": {
    "inputs": {
      "x": 672,
      "y": 0,
      "operation": "add",
      "destination": [
        "13",
        0
      ],
      "source": [
        "12",
        0
      ]
    },
    "class_type": "MaskComposite",
    "_meta": {
      "title": "MaskComposite (Right)"
    }
  },
  "23": {
    "inputs": {
      "model": [
        "4",
        0
      ],
      "base_mask": [
        "11",
        0
      ],
      "cond_1": [
        "10",
        0
      ],
      "mask_1": [
        "14",
        0
      ]
    },
    "class_type": "AttentionCouple|cgem156",
    "_meta": {
      "title": "Attention Couple 🍌"
    }
  },
  "27": {
    "inputs": {
      "images": [
        "8",
        0
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  }
}

**Comment by yelnady** [comment]
I have added a SaveImage node

**Comment by fofr** [comment]
Do you have a UI version too?

**Comment by yelnady** [comment]
Sure:
{
  "last_node_id": 31,
  "last_link_id": 53,
  "nodes": [
    {
      "id": 11,
      "type": "MaskComposite",
      "pos": [
        15,
        -283
      ],
      "size": {
        "0": 315,
        "1": 126
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "destination",
          "type": "MASK",
          "link": 15
        },
        {
          "name": "source",
          "type": "MASK",
          "link": 13
        }
      ],
      "outputs": [
        {
          "name": "MASK",
          "type": "MASK",
          "links": [
            45
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "MaskComposite (Left)",
      "properties": {
        "Node name for S&R": "MaskComposite"
      },
      "widgets_values": [
        0,
        0,
        "add"
      ]
    },
    {
      "id": 4,
      "type": "CheckpointLoaderSimple",
      "pos": [
        -938,
        -262
      ],
      "size": {
        "0": 413.80047607421875,
        "1": 99.298095703125
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            36
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            3,
            5,
            10
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            8
          ],
          "slot_index": 2
        }
      ],
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "dreamshaperXL_lightningDPMSDE.safetensors"
      ]
    },
    {
      "id": 27,
      "type": "PreviewImage",
      "pos": [
        828,
        -15
      ],
      "size": [
        622.8980053349369,
        669.8738981552675
      ],
      "flags": {
        "collapsed": false
      },
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 51
        }
      ],
      "properties": {
        "Node name for S&R": "PreviewImage"
      }
    },
    {
      "id": 7,
      "type": "CLIPTextEncode",
      "pos": [
        -423,
        457
      ],
      "size": {
        "0": 415.9034118652344,
        "1": 177.715087890625
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 5
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            43
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "bad eyes, bad hands, no legs, no eye contact"
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 5,
      "type": "EmptyLatentImage",
      "pos": [
        -847,
        -53
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            2
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        1344,
        768,
        1
      ]
    },
    {
      "id": 13,
      "type": "SolidMask",
      "pos": [
        -409,
        -313
      ],
      "size": {
        "0": 302.18865966796875,
        "1": 106
      },
      "flags": {
        "collapsed": false
      },
      "order": 2,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "MASK",
          "type": "MASK",
          "links": [
            15,
            16
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "SolidMask:Base"
      },
      "widgets_values": [
        0,
        1344,
        768
      ]
    },
    {
      "id": 12,
      "type": "SolidMask",
      "pos": [
        -415,
        -149
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "outputs": [
        {
          "name": "MASK",
          "type": "MASK",
          "links": [
            13,
            14
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "SolidMask"
      },
      "widgets_values": [
        1,
        672,
        768
      ]
    },
    {
      "id": 14,
      "type": "MaskComposite",
      "pos": [
        15,
        -106
      ],
      "size": {
        "0": 315,
        "1": 126
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "destination",
          "type": "MASK",
          "link": 16
        },
        {
          "name": "source",
          "type": "MASK",
          "link": 14
        }
      ],
      "outputs": [
        {
          "name": "MASK",
          "type": "MASK",
          "links": [
            47
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "MaskComposite (Right)",
      "properties": {
        "Node name for S&R": "MaskComposite"
      },
      "widgets_values": [
        672,
        0,
        "add"
      ]
    },
    {
      "id": 23,
      "type": "AttentionCouple|cgem156",
      "pos": [
        438,
        -345
      ],
      "size": {
        "0": 159.60000610351562,
        "1": 86
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 36
        },
        {
          "name": "base_mask",
          "type": "MASK",
          "link": 45
        },
        {
          "name": "cond_1",
          "type": "CONDITIONING",
          "link": 46
        },
        {
          "name": "mask_1",
          "type": "MASK",
          "link": 47,
          "slot_index": 3
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            37
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "AttentionCouple|cgem156"
      }
    },
    {
      "id": 3,
      "type": "KSampler",
      "pos": [
        443,
        -133
      ],
      "size": {
        "0": 315,
        "1": 474
      },
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 37
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 42
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 43
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 2
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            7
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        934436605939168,
        "randomize",
        4,
        2,
        "dpmpp_sde",
        "karras",
        1
      ]
    },
    {
      "id": 6,
      "type": "CLIPTextEncode",
      "pos": [
        -425,
        35
      ],
      "size": {
        "0": 422.84503173828125,
        "1": 164.31304931640625
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 3
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            42
          ],
          "slot_index": 0
        }
      ],
      "title": "CLIP Text Encode (Left)",
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "boy and girl squirrels swimming in the red sea. First, A curious bushy-tailed squirrel. He has big, round eyes sparkling with mischief and a giant acorn clutched in one tiny paw. He is wearing a hat. The hat has a wide brim that dips slightly in the front, perfect for shielding his eyes from the sun. ([Pixar Style]).  "
      ]
    },
    {
      "id": 10,
      "type": "CLIPTextEncode",
      "pos": [
        -424,
        248
      ],
      "size": [
        417.0504125838444,
        159.03552475181158
      ],
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 10
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            46
          ],
          "slot_index": 0
        }
      ],
      "title": "CLIP Text Encode (Right)",
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "boy and girl squirrels swimming in the red sea. A tiny squirrel girl, Pixar style, with big, bright eyes sparkling with mischief. Her brown fur is accented by a cute pink bow perched on one ear, and a soft, pink ribbon adorns her bushy tail.  She has a mischievous grin and a white chest.  She's mismatched as ever, with one striped sock and one polka-dotted sock (but this time, the polka-dots are pink!). ([Pixar Style]).  "
      ]
    },
    {
      "id": 8,
      "type": "VAEDecode",
      "pos": [
        863,
        -181
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {
        "collapsed": false
      },
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 7
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 8
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            51,
            53
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 31,
      "type": "SaveImage",
      "pos": [
        1227.837271698446,
        -174.39031994706994
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 53
        }
      ],
      "properties": {},
      "widgets_values": [
        "ComfyUI"
      ]
    }
  ],
  "links": [
    [
      2,
      5,
      0,
      3,
      3,
      "LATENT"
    ],
    [
      3,
      4,
      1,
      6,
      0,
      "CLIP"
    ],
    [
      5,
      4,
      1,
      7,
      0,
      "CLIP"
    ],
    [
      7,
      3,
      0,
      8,
      0,
      "LATENT"
    ],
    [
      8,
      4,
      2,
      8,
      1,
      "VAE"
    ],
    [
      10,
      4,
      1,
      10,
      0,
      "CLIP"
    ],
    [
      13,
      12,
      0,
      11,
      1,
      "MASK"
    ],
    [
      14,
      12,
      0,
      14,
      1,
      "MASK"
    ],
    [
      15,
      13,
      0,
      11,
      0,
      "MASK"
    ],
    [
      16,
      13,
      0,
      14,
      0,
      "MASK"
    ],
    [
      36,
      4,
      0,
      23,
      0,
      "MODEL"
    ],
    [
      37,
      23,
      0,
      3,
      0,
      "MODEL"
    ],
    [
      42,
      6,
      0,
      3,
      1,
      "CONDITIONING"
    ],
    [
      43,
      7,
      0,
      3,
      2,
      "CONDITIONING"
    ],
    [
      45,
      11,
      0,
      23,
      1,
      "MASK"
    ],
    [
      46,
      10,
      0,
      23,
      2,
      "CONDITIONING"
    ],
    [
      47,
      14,
      0,
      23,
      3,
      "MASK"
    ],
    [
      51,
      8,
      0,
      27,
      0,
      "IMAGE"
    ],
    [
      53,
      8,
      0,
      31,
      0,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 1.4641000000000006,
      "offset": [
        -39.908787476057334,
        327.9269422747797
      ]
    }
  },
  "version": 0.4
}


Here are some images as well: 
image
image
image
image
image

**Comment by fofr** [comment]
Ok, I'm seeing the same error with your workflow as I did with mine (which I wasn't sure if I'd put together correctly):

Screenshot 2024-06-05 at 16 01 30

Any ideas?

**Comment by fofr** [comment]
Ah, that error happens if you run in `--gpu-only` mode

**Comment by fofr** [comment]
@yelnady Is this the only node in this set that you use? Or are the others useful too?

**Comment by yelnady** [comment]
Okay, I have been debugging this error since yesterday, it only happens with `--gpu-only`. I wasn't aware you updated start.sh with --gpu-only. If I switch to [--highvram | --normalvram | --lowvram | --novram | --cpu], it goes away.

I have already submitted an issue on the node's repo. 

However, as you asked, I am only utilizing the attention couple node from this pack, do you think you can add the repo that contains this node only: https://github.com/laksjdjf/attention-couple-ComfyUI? I can push another PR.

{
    "repo": "https://github.com/laksjdjf/attention-couple-ComfyUI",
    "commit": "818b4a2"
  }

**I tested attention-couple-ComfyUI with `--gpu-only`, and it worked fine with the expected results.** 

Here's an updated API Workflow: 

{
  "3": {
    "inputs": {
      "seed": 541202993035792,
      "steps": 4,
      "cfg": 2,
      "sampler_name": "dpmpp_sde",
      "scheduler": "karras",
      "denoise": 1,
      "model": [
        "39",
        0
      ],
      "positive": [
        "39",
        1
      ],
      "negative": [
        "39",
        2
      ],
      "latent_image": [
        "5",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "4": {
    "inputs": {
      "ckpt_name": "dreamshaperXL_lightningDPMSDE.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "5": {
    "inputs": {
      "width": 1024,
      "height": 1024,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "6": {
    "inputs": {
      "text": "- boy and girl squirrels swimming in the red sea. First, A curious bushy-tailed squirrel. He has big, round eyes sparkling with mischief and a giant acorn clutched in one tiny paw. He is wearing a hat. The hat has a wide brim that dips slightly in the front, perfect for shielding his eyes from the sun. ([Pixar Style]).  \n",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Left)"
    }
  },
  "7": {
    "inputs": {
      "text": "bad eyes, bad hands, no legs, no eye contact",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "10": {
    "inputs": {
      "text": "- boy and girl squirrels swimming in the red sea. A tiny squirrel girl, Pixar style, with big, bright eyes sparkling with mischief. Her brown fur is accented by a cute pink bow perched on one ear, and a soft, pink ribbon adorns her bushy tail.  She has a mischievous grin and a white chest.  She's mismatched as ever, with one striped sock and one polka-dotted sock (but this time, the polka-dots are pink!). ([Pixar Style]).  ",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Right)"
    }
  },
  "11": {
    "inputs": {
      "x": 0,
      "y": 0,
      "operation": "add",
      "destination": [
        "13",
        0
      ],
      "source": [
        "12",
        0
      ]
    },
    "class_type": "MaskComposite",
    "_meta": {
      "title": "MaskComposite (Left)"
    }
  },
  "12": {
    "inputs": {
      "value": 1,
      "width": 512,
      "height": 1024
    },
    "class_type": "SolidMask",
    "_meta": {
      "title": "SolidMask"
    }
  },
  "13": {
    "inputs": {
      "value": 0,
      "width": 1024,
      "height": 1024
    },
    "class_type": "SolidMask",
    "_meta": {
      "title": "SolidMask"
    }
  },
  "14": {
    "inputs": {
      "x": 512,
      "y": 0,
      "operation": "add",
      "destination": [
        "13",
        0
      ],
      "source": [
        "12",
        0
      ]
    },
    "class_type": "MaskComposite",
    "_meta": {
      "title": "MaskComposite (Right)"
    }
  },
  "27": {
    "inputs": {
      "images": [
        "8",
        0
      ]
    },
    "class_type": "PreviewImage",
    "_meta": {
      "title": "Preview Image"
    }
  },
  "31": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  },
  "36": {
    "inputs": {
      "strength": 1,
      "set_cond_area": "default",
      "conditioning": [
        "6",
        0
      ],
      "mask": [
        "11",
        0
      ]
    },
    "class_type": "ConditioningSetMask",
    "_meta": {
      "title": "Conditioning (Set Mask)"
    }
  },
  "37": {
    "inputs": {
      "strength": 1,
      "set_cond_area": "default",
      "conditioning": [
        "10",
        0
      ],
      "mask": [
        "14",
        0
      ]
    },
    "class_type": "ConditioningSetMask",
    "_meta": {
      "title": "Conditioning (Set Mask)"
    }
  },
  "38": {
    "inputs": {
      "conditioning_1": [
        "36",
        0
      ],
      "conditioning_2": [
        "37",
        0
      ]
    },
    "class_type": "ConditioningCombine",
    "_meta": {
      "title": "Conditioning (Combine)"
    }
  },
  "39": {
    "inputs": {
      "mode": "Attention",
      "model": [
        "4",
        0
      ],
      "positive": [
        "38",
        0
      ],
      "negative": [
        "38",
        0
      ]
    },
    "class_type": "Attention couple",
    "_meta": {
      "title": "Load Attention couple"
    }
  }
}

**Comment by yelnady** [comment]
@fofr Any updates? I hope you can please add:

{
"repo": "https://github.com/laksjdjf/attention-couple-ComfyUI",
"commit": "818b4a2"
}

Do you want me to do a PR?

**Comment by fofr** [comment]
@yelnady Yes, please raise a PR for that node only 🙏

**Pull request closed without merging**
