### PR TITLE
Add Attention Couple Node

### PR DESCRIPTION
**Pull request by yelnady**
Request for adding the Attention Couple Node, as discussed in a previous PR. 
Thanks

### CODE REVIEW

**Comment by yelnady** [comment]
Also, the updated node pack that contains the attention couple node is fixed now. I prefer to use the `cgem156-ComfyUI` as it's better maintained (not archived), and provides more features and enhanced image composition. 

Here's it to try and up to you to decide: 
{
    "repo": "https://github.com/laksjdjf/cgem156-ComfyUI",
    "commit": "1f5533f"
  }

If `cgem156-ComfyUI` works fine now with no dtype errors, please let me know if possible to use it. 
Thanks

**Comment by fofr** [comment]
Thanks, good to see it's been fixed, I'll continue reviewing – I need to double check what all the other nodes do.

**Comment by fofr** [comment]
(I love regional prompting like this, so this will make it in, in some form or another)

**Comment by fofr** [comment]
I opted for https://github.com/laksjdjf/attention-couple-ComfyUI as the library of nodes was slow to start. Sorry for the delay in adding this, see the commit:

https://github.com/fofr/cog-comfyui/commit/2bdc76dc1cb001bc1669d0d0c40467faac10063e

**Pull request closed without merging**
