### PR TITLE
fix 403 error using requests instead of urllib

### PR DESCRIPTION
**Pull request by davut**
urllib does not let you download some urls so using requests is suggested on those cases

example url input that's not working with the current urllib:  https://roomai.whaleapps.co/image.jpg

### CODE REVIEW

**Comment by davut** [comment]
Hey @fofr is this going to be considered or nah?

**Comment by fofr** [comment]
Thanks for the nudge. I'll review this early next week. Looks good.

**Comment by davut** [comment]
Thanks

**Comment by fofr** [comment]
I've merged and push this model to Replicate now:
https://replicate.com/fofr/any-comfyui-workflow/versions/e300f182eb742fc0da05f0609e5176934c9aaceabb5e6d53ecf2632d78ada22c

Thank you for this fix 🙏

**Comment by davut** [comment]
Thank you for considering it!

**Pull request merged**
